# Generated by Django 5.2.6 on 2025-09-05 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='useranme',
            new_name='username',
        ),
    ]
